# Generated by Django 4.2.3 on 2023-08-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Особенные приметы')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='special_notes',
        ),
        migrations.AddField(
            model_name='car',
            name='special_notes',
            field=models.ManyToManyField(blank=True, null=True, to='cars.special_notes'),
        ),
    ]
