# Generated by Django 4.2.3 on 2023-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, help_text='Км', verbose_name='Пробег'),
        ),
    ]
