# Generated by Django 4.2.4 on 2023-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ruletype',
            field=models.CharField(choices=[('left', 'левый'), ('right', 'правый')], default='left', max_length=5, verbose_name='Тип руля'),
        ),
    ]
