# Generated by Django 4.2.3 on 2023-08-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_special_notes_remove_car_special_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('white', 'белый'), ('red', 'красный'), ('blue', 'синий'), ('black', 'черный'), ('silver', 'серебристый'), ('gray', 'серый'), ('green', 'зеленый'), ('yellow', 'желтый'), ('orange', 'оранжевый'), ('brown', 'коричневый'), ('gold', 'золотистый'), ('pink', 'розовый'), ('beige', 'бежевый'), ('violet', 'фиолетовый'), ('burgundy', 'бордовый')], max_length=15, verbose_name='цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('petrol', 'бензин'), ('diesel', 'дизель'), ('hybrid', 'гибрид'), ('electric fuel', 'электро')], max_length=13, verbose_name='топливо'),
        ),
    ]
