# Generated by Django 4.2.3 on 2023-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_color_alter_car_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('USD', 'В долларах'), ('KGZ', 'В сомах')], default='USD', max_length=11, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('machine', 'автомат'), ('tiptronic', 'типтроник'), ('mechanics', 'механика'), ('variable speed', 'вариатор'), ('robot', 'робот')], max_length=15, verbose_name='коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='special_notes',
            field=models.ManyToManyField(to='cars.special_notes'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(blank=True, choices=[('yes', 'есть'), ('no', 'нет')], default=False, max_length=5, verbose_name='наличие вин кода'),
        ),
    ]
