# Generated by Django 4.2.4 on 2023-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_ruletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='additional_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительние приметы'),
        ),
    ]
