# Generated by Django 4.2.3 on 2023-08-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_currency_alter_car_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ruletype',
            field=models.CharField(choices=[('right', 'правый'), ('left', 'левый')], default='left', max_length=5, verbose_name='Тип руля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(blank=True, choices=[('yes', 'есть VIN-код'), ('no', 'нет VIN-код')], default=False, max_length=5, verbose_name='наличие вин кода'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
        ),
    ]
