# Generated by Django 4.2.3 on 2023-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_ruletype_alter_car_vin_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(related_name='car', to='cars.carphoto'),
        ),
    ]
