# Generated by Django 4.2.4 on 2023-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.URLField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
