# Generated by Django 4.2.3 on 2023-08-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carphoto_car_car_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
        ),
    ]
