# Generated by Django 4.2.3 on 2023-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_photos_carphoto_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='описание'),
        ),
    ]
