# Generated by Django 4.2.3 on 2023-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
