# Generated by Django 4.2.3 on 2023-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_notes',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Особенные приметы'),
        ),
    ]
