# Generated by Django 4.2.3 on 2023-08-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_special_notes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='cars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carmake'),
        ),
        migrations.AlterField(
            model_name='special_notes',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Особенные приметы'),
        ),
    ]
