# Generated by Django 4.2.3 on 2023-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'В долларах'), ('KGZ', 'В сомах')], default='USD', max_length=11, verbose_name='валюта'),
        ),
    ]
