# Generated by Django 4.2.3 on 2023-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_number',
            field=models.CharField(choices=[('hide', 'скрыть номер телефона'), ('show', 'показать номер телефона')], max_length=11, null=True, verbose_name='Номер телефона'),
        ),
    ]
