# Generated by Django 4.2.3 on 2023-08-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_hide_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hide_number',
        ),
    ]
