# Generated by Django 4.2.3 on 2023-08-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Part_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=100)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seller_contact', models.CharField(max_length=100)),
                ('car_part_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carparts', to='spare_part.car_part_brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare_part.carpart')),
            ],
        ),
    ]
