# Generated by Django 4.2.2 on 2023-08-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_part_brand',
            options={'verbose_name_plural': 'Car part Brand'},
        ),
        migrations.AlterModelOptions(
            name='carpart',
            options={'verbose_name_plural': 'Car part'},
        ),
        migrations.AlterModelOptions(
            name='carpartimage',
            options={'verbose_name_plural': 'Car part image'},
        ),
    ]
