# Generated by Django 4.2.4 on 2023-09-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_part', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='carpart',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Км', verbose_name='Количество просмотров'),
        ),
    ]
