# Generated by Django 4.2.4 on 2023-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_part', '0004_carpart_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='в наличий'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='seller_contact',
            field=models.CharField(max_length=100, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='vendor_code',
            field=models.CharField(max_length=20, null=True, verbose_name='сериный номер'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='year',
            field=models.PositiveIntegerField(verbose_name='год'),
        ),
    ]
