# Generated by Django 4.2.4 on 2023-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_part', '0005_alter_carpart_description_alter_carpart_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
